name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #  - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libeigen3-dev libtaglib-cil-dev libavcodec-dev \
            libavformat-dev libavutil-dev libavresample-dev libsamplerate0-dev \
            libyaml-dev libchromaprint-dev libfftw3-dev

      - name: Build streaming_extractor_music
        run: |
          git clone --depth=1 https://github.com/MTG/essentia.git
          cd essentia
          chmod +x ./waf
          ./waf configure --with-example=streaming_extractor_music
          ./waf
