name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install yasm

      - name: Clone essentia repository
        run: |
          git clone --depth=1 --branch=v2.1_beta2 https://github.com/MTG/essentia.git

      - name: Apply patches
        run: |
          cd essentia
          patch -p1 < ../patches/*.patch

      - name: Build and install dependencies
        run: |
          cd essentia
          ./packaging/build_3rdparty_static_debian.sh

      - name: Build streaming_extractor_music
        run: |
          cd essentia
          python2 waf configure --with-example=streaming_extractor_music --with-static-examples
          python2 waf

      - name: Gather build artifacts
        run: |
          mkdir artifacts
          cp essentia/AUTHORS artifacts/
          cp essentia/COPYING.txt artifacts/
          mv essentia/build/src/examples/streaming_extractor_music artifacts

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: essentia-extractor-${{ runner.os }}
          path: artifacts/
